name: Go CI/CD

on:
  push:
    branches:
      - main
      - new-feature
  pull_request:
    branches:
      - main
      - new-feature

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Clean cache directories before restoring
      run: |
        rm -rf ~/.cache/go-build
        rm -rf ~/go/pkg/mod

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod download

    - name: Update Go dependencies
      run: go get -u ./...

    - name: Install SQLite3
      run: sudo apt-get update && sudo apt-get install -y sqlite3 libsqlite3-dev

    - name: Set up database schema
      run: |
        sqlite3 "${{ github.workspace }}/scheduler.db" < schema.sql

    - name: Build the application
      run: go build -v -o app ./cmd

    - name: Start the application
      env:
        TODO_PORT: 7540
        TODO_DBFILE: ${{ github.workspace }}/scheduler.db
        TODO_PASSWORD: ""
      run: |
        nohup ./app &
        sleep 10

    - name: Run tests
      env:
        TODO_DBFILE: ${{ github.workspace }}/scheduler.db
        TODO_PASSWORD: ""
      run: |
        go test -v ./...

    - name: Lint code
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.52.2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/new-feature'
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/go_final_project:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/go_final_project:latest