name: Go CI/CD

on:
  push:
    branches:
      - main
      - new-feature
  pull_request:
    branches:
      - main
      - new-feature

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TODO_PORT: 7540
      TODO_DBFILE: scheduler.db
      TODO_PASSWORD: ${{ secrets.TODO_PASSWORD }}  # Заменил на секрет для безопасности

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod download

    - name: Set up database schema
      run: |
        sqlite3 ${{ env.TODO_DBFILE }} < schema.sql

    - name: Build the application
      run: go build -v -o app ./cmd/main.go

    - name: Start the application
      run: |
        nohup ./app &
        sleep 5 

    - name: Run tests
      run: go test -v ./...

    - name: Lint code
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.52.2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/new-feature'
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/go_final_project:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/go_final_project:latest
