name: Go CI/CD

on:
  push:
    branches:
      - main
      - new-feature
  pull_request:
    branches:
      - main
      - new-feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.52.2

    - name: Build Docker image
      run: docker build -t vladimirvereschagin/go_final_project:latest .

    - name: Push Docker image to DockerHub
      if: github.ref == 'refs/heads/main'
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker push vladimirvereschagin/go_final_project:latest