name: Go CI/CD

on:
  push:
    branches:
      - main
      - new-feature
  pull_request:
    branches:
      - main
      - new-feature

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Install SQLite3
      run: sudo apt-get update && sudo apt-get install -y sqlite3 libsqlite3-dev

    - name: Set up database schema
      run: |
        sqlite3 "${{ github.workspace }}/scheduler.db" < schema.sql

    - name: Build the application
      run: go build -v -o app ./cmd

    - name: Start the application
      env:
        TODO_PORT: 7540
        TODO_DBFILE: ${{ github.workspace }}/scheduler.db
        TODO_PASSWORD: ""
      run: |
        nohup ./app &
        sleep 10

    - name: Run tests
      env:
        TODO_DBFILE: ${{ github.workspace }}/scheduler.db
        TODO_PASSWORD: ""
      run: |
        go test -v ./...

    - name: Lint code
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        skip-cache: true
      env:
        GO111MODULE: 'on'
        GOPROXY: 'https://proxy.golang.org,direct'

    - name: Log in to DockerHub
      if: github.ref_name == 'main' || github.ref_name == 'new-feature'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set up QEMU
      if: github.ref_name == 'main' || github.ref_name == 'new-feature'
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      if: github.ref_name == 'main' || github.ref_name == 'new-feature'
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      if: github.ref_name == 'main' || github.ref_name == 'new-feature'
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/scheduler:latest