name: Go CI

on:
  push:
    branches: 
      - main
      - new-feature
  pull_request:
    branches: 
      - main
      - new-feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build -v ./cmd/main.go

    - name: Set up database schema
      run: |
        sqlite3 scheduler.db < schema.sql

    - name: Start server
      run: |
        nohup go run ./cmd/main.go & # Запуск сервера в фоновом режиме
      timeout-minutes: 10

    - name: Run tests
      run: go test -v ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.52.2